#!/usr/bin/env bash
# envoi 5 paquets (-c 5) ICMP (Internet Control Message Protocol) à une adresse IP spécifiée en argument ($1) pour vérifier si l'hôte est actif
if [ ! "$1" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
